=== davidlmorton/ptero-workflow/ptero_workflow/api/v1/schemas/post_workflow.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "POST /v1/workflows",

    "type": "object",
    "properties": {
        "inputs": { "$ref": "#/definitions/inputDictionary" },
        "tasks": { "$ref": "#/definitions/taskDictionary" },
        "edges": { "type": "array" },
        "parallelBy": { "$ref": "#/definitions/name" }
    },
    "required": ["inputs", "tasks", "edges"],
    "additionalProperties": false,

    "definitions": {
        "name": {
            "type": "string",
            "minLength": 1
        },

        "inputType": { "oneOf": [
            { "$ref": "#/definitions/name" },
            {
                "type": "array",
                "items": { "$ref": "#/definitions/inputType" }
            }
        ]},

        "inputDictionary": {
            "type": "object",
            "patternProperties": {
                "^.+$": { "$ref": "#/definitions/inputType" }
            },
            "additionalProperties": false
        },

        "taskDictionary": {
            "type": "object",
            "patternProperties": {
                "^.+$": { "$ref": "#/definitions/task" }
            },
            "additionalProperties": false
        },

        "task": {
            "type": "object",
            "properties": {
                "methods": { "type": "array" },
                "parallelBy": { "$ref": "#/definitions/name" }
            },
            "additionalProperties": false
        }
    }
}

=== davidlmorton/ptero-workflow/tests/api/v1/system_tests/nested_parallel_by_operation_orthogonal_inputs/submit.json
{
    "parallelBy": "in_outer_parallel",

    "tasks": {
        "A": {
            "methods": [
                {
                    "name": "execute",
                    "service": "ShellCommand",
                    "parameters": {
                        "commandLine": ["cat"],
                        "user": "{{ user }}",
                        "workingDirectory": "{{ workingDirectory }}"
                    }
                }
            ],
            "parallelBy": "kitten_name"
        }
    },

    "edges": [
        {
            "source": "input connector",
            "destination": "A",
            "sourceProperty": "in_outer_parallel",
            "destinationProperty": "animal_type"
        },
        {
            "source": "A",
            "destination": "output connector",
            "sourceProperty": "animal_type",
            "destinationProperty": "out_outer_parallel"
        },

        {
            "source": "input connector",
            "destination": "A",
            "sourceProperty": "in_inner_parallel",
            "destinationProperty": "kitten_name"
        },
        {
            "source": "A",
            "destination": "output connector",
            "sourceProperty": "kitten_name",
            "destinationProperty": "out_inner_parallel"
        }
    ],

    "inputs": {
        "in_outer_parallel": ["kittens", "puppies"],
        "in_inner_parallel": ["Simba", "Tabby", "Emilio"]
    }
}
